version: "2.1"

services:

  app:
    image: smileinnovation/imannotate
    ports:
    - 8080:8000
    environment:
      DB_USER: mongouser
      DB_PASS: mongopwd
      DB_HOST: database
      DB_NAME: imannotate
      DB_AUTH: admin
    # if you are using docker-auto-dnsmasq or
    # if you want to be sure that current hostname
    # in the docker container is set, you can
    # uncomment the "hostname" attribute and modify it.
    #
    # See https://github.com/metal3d/docker-auto-dnsmasq
    #
    # hostname: imannotate.docker
        
  database:
    image: mongo
    volumes:
      - db-prod:/data/db
    privileged: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
        

volumes:
  db-prod:
